package util;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class FirstFollow{
	public final String Name;
	public final String CaseSensitive;
	public final String About;
	public final String Author;
	public final String Version;
	public final String StartSymbol;
	private HashMap<String, HashSet<String>> first;
	private HashMap<String, HashSet<String>> follow;
	private static FirstFollow instance;

    private FirstFollow(){
		this.Name = "PBL Compiladores";
		this.CaseSensitive = "True";
		this.About = "Grammar";
		this.Author = "Abel Galvão, Caique Trindade, Emerson Souza, Felipe Damascena, Pedro Brandão, Ramon Silva, Solenir Figuerêdo, Victor Souza";
		this.Version = "1.0";
		this.StartSymbol = "<Inicio>";
		this.first = new HashMap<>();
		this.first.put("ArgumentoLR2_1", new HashSet<>(Arrays.asList("Id", "false", "true")));
		this.first.put("Read", new HashSet<>(Arrays.asList("read")));
		this.first.put("OperadorLogico", new HashSet<>(Arrays.asList("&&", "||")));
		this.first.put("ArgumentoLR2", new HashSet<>(Arrays.asList("false", "true", "!")));
		this.first.put("Corpo", new HashSet<>(Arrays.asList("}", "read", "while", "return", "local", "print", "var", "Id", "if", "global")));
		this.first.put("Var", new HashSet<>(Arrays.asList("", "var")));
		this.first.put("Tipo", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.first.put("Print", new HashSet<>(Arrays.asList("print")));
		this.first.put("ExpressaoLogicaRelacional", new HashSet<>(Arrays.asList("Numero", "(", "local", "false", "true", "global", "!", "Id", "++", "String", "--")));
		this.first.put("Struct2", new HashSet<>(Arrays.asList(";", ",")));
		this.first.put("OperadorRelacional", new HashSet<>(Arrays.asList(">", "<", "!=", ">=", "<=", "==")));
		this.first.put("Identificador4", new HashSet<>(Arrays.asList(".", "")));
		this.first.put("Const", new HashSet<>(Arrays.asList("", "const")));
		this.first.put("ExpressaoLR3", new HashSet<>(Arrays.asList("||", "&&", "")));
		this.first.put("IdentificadorAritmetico3", new HashSet<>(Arrays.asList(".", "[", "(")));
		this.first.put("CodigosRetornos", new HashSet<>(Arrays.asList("local", "Numero", ";", "(", "Id", "global", "++", "--")));
		this.first.put("Escopo", new HashSet<>(Arrays.asList("global", "local")));
		this.first.put("Comandos", new HashSet<>(Arrays.asList("local", "print", "read", "while", "Id", "return", "if", "global")));
		this.first.put("Vetor2", new HashSet<>(Arrays.asList("[", "")));
		this.first.put("T2", new HashSet<>(Arrays.asList("", "/", "*")));
		this.first.put("ListaParametros", new HashSet<>(Arrays.asList("Numero", "Id", "local", "String", "global")));
		this.first.put("Para2", new HashSet<>(Arrays.asList("[", "")));
		this.first.put("Print1", new HashSet<>(Arrays.asList("Numero", "Id", "global", "String", "local")));
		this.first.put("IdentificadorSemFuncao", new HashSet<>(Arrays.asList("Id", "local", "global")));
		this.first.put("PrintFim", new HashSet<>(Arrays.asList(")")));
		this.first.put("Identificador2", new HashSet<>(Arrays.asList(".", "[", "")));
		this.first.put("TipoStruct", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.first.put("T", new HashSet<>(Arrays.asList("(", "Numero")));
		this.first.put("ExpressaoLR", new HashSet<>(Arrays.asList("Numero", "(", "local", "--", "true", "++", "!", "Id", "global", "String", "false")));
		this.first.put("ArgumentoLR3", new HashSet<>(Arrays.asList("local", "Numero", "(", "global", "Id", "++", "String", "--")));
		this.first.put("Identificador", new HashSet<>(Arrays.asList("Id", "local", "global")));
		this.first.put("E2", new HashSet<>(Arrays.asList("-", "+", "")));
		this.first.put("Procedimento", new HashSet<>(Arrays.asList("procedure")));
		this.first.put("IdVar", new HashSet<>(Arrays.asList("Id")));
		this.first.put("Struct", new HashSet<>(Arrays.asList("", "typedef")));
		this.first.put("Valor", new HashSet<>(Arrays.asList("Id", "Numero", "String", "Boolean")));
		this.first.put("ContListaParametros", new HashSet<>(Arrays.asList("", ",")));
		this.first.put("Start", new HashSet<>(Arrays.asList("start")));
		this.first.put("Var3", new HashSet<>(Arrays.asList("}", "int", "boolean", "Id", "string", "real")));
		this.first.put("IdConst", new HashSet<>(Arrays.asList("Id")));
		this.first.put("Const3", new HashSet<>(Arrays.asList("int", "boolean", "Id", "real", "string", " } ")));
		this.first.put("Funcao", new HashSet<>(Arrays.asList("function")));
		this.first.put("Const2", new HashSet<>(Arrays.asList(" , ", " ; ")));
		this.first.put("TipoConst", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.first.put("Struct3", new HashSet<>(Arrays.asList("}", "int", "boolean", "Id", "string", "real")));
		this.first.put("Parametro", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.first.put("IdStruct", new HashSet<>(Arrays.asList("Id")));
		this.first.put("Var2", new HashSet<>(Arrays.asList("=", "[", ".", ",", ";")));
		this.first.put("F", new HashSet<>(Arrays.asList("(", "Numero")));
		this.first.put("Var4", new HashSet<>(Arrays.asList(";", ",")));
		this.first.put("ExpressaoLR2", new HashSet<>(Arrays.asList(">=", "<", "<=", "!=", "||", "==", "&&", ">")));
		this.first.put("F2", new HashSet<>(Arrays.asList("{")));
		this.first.put("IdentificadorComandos2_1", new HashSet<>(Arrays.asList("Numero", "(", "local", "Boolean", "++", "Id", "global", "String", "--")));
		this.first.put("IndiceVetor", new HashSet<>(Arrays.asList("Id", "IntPos", "global", "local")));
		this.first.put("TipoVar", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.first.put("IdentificadorComandos2", new HashSet<>(Arrays.asList("=", "(")));
		this.first.put("Para1", new HashSet<>(Arrays.asList(")", ",")));
		this.first.put("ExpressaoAritmetica2", new HashSet<>(Arrays.asList("*", "/", "--", "++")));
		this.first.put("AuxRead", new HashSet<>(Arrays.asList(")", ",")));
		this.first.put("Read1", new HashSet<>(Arrays.asList("Id", "global", "local")));
		this.first.put("Extends", new HashSet<>(Arrays.asList("extends", "{")));
		this.first.put("Identificador3", new HashSet<>(Arrays.asList(".", "[", "(")));
		this.first.put("AuxPrint", new HashSet<>(Arrays.asList(")", ",")));
		this.first.put("Para3", new HashSet<>(Arrays.asList("[", "")));
		this.first.put("ArgumentoLR", new HashSet<>(Arrays.asList("Numero", "(", "local", "--", "true", "++", "!", "Id", "global", "String", "false")));
		this.first.put("ReadFim", new HashSet<>(Arrays.asList(")")));
		this.first.put("ListaParametros2", new HashSet<>(Arrays.asList("Numero", "Id", "global", "String", "local")));
		this.first.put("Inicio", new HashSet<>(Arrays.asList("const", "procedure", "var", "function", "typedef")));
		this.first.put("Laco", new HashSet<>(Arrays.asList("while")));
		this.first.put("CondEnd", new HashSet<>(Arrays.asList("else", "")));
		this.first.put("GeraFuncaoeProcedure", new HashSet<>(Arrays.asList("", "procedure", "function")));
		this.first.put("Condicional", new HashSet<>(Arrays.asList("if")));
		this.first.put("ComandosReturn", new HashSet<>(Arrays.asList("return")));
		this.first.put("IdentificadorAritmetico", new HashSet<>(Arrays.asList("Id", "local", "global")));
		this.first.put("IdentificadorComandos", new HashSet<>(Arrays.asList("Id", "global", "local")));
		this.first.put("Corpo2", new HashSet<>(Arrays.asList("read", "while", "", "return", "local", "print", "Id", "if", "global")));
		this.first.put("Vetor", new HashSet<>(Arrays.asList("[", ".")));
		this.first.put("ExpressaoAritmetica", new HashSet<>(Arrays.asList("Numero", "--", "++", "Id", "global", "(", "local")));
		this.follow = new HashMap<>();
		this.follow.put("ArgumentoLR2_1", new HashSet<>(Arrays.asList(">", "<", "||", "++", "==", "<=", "!", "Id", "String", "Numero", "!=", "(", "global", "local", ">=", "true", "false", "&&", "--")));
		this.follow.put("Read", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("OperadorLogico", new HashSet<>(Arrays.asList("Numero", "(", "local", "--", "true", "++", "!", "Id", "global", "String", "false")));
		this.follow.put("ArgumentoLR2", new HashSet<>(Arrays.asList(">", "<", "||", "++", "==", "<=", "!", "Id", "String", "Numero", "!=", "(", "--", "local", "false", "true", ">=", "&&", "global")));
		this.follow.put("IdentificadorComandos2", new HashSet<>(Arrays.asList("Id", "local", "global")));
		this.follow.put("Var", new HashSet<>(Arrays.asList("const", "function", "while", "return", "local", "read", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("Tipo", new HashSet<>(Arrays.asList("Id", "function")));
		this.follow.put("Print", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("ExpressaoLogicaRelacional", new HashSet<>(Arrays.asList("Numero", "while", "(", "if", "local", "false", "true", "global", "!", "Id", "++", "String", "--")));
		this.follow.put("Struct2", new HashSet<>(Arrays.asList("typedef", "procedure", "var", "function", "const")));
		this.follow.put("OperadorRelacional", new HashSet<>(Arrays.asList("Numero", "(", "local", "false", "true", "global", "!", "Id", "++", "String", "--")));
		this.follow.put("Identificador4", new HashSet<>(Arrays.asList(";", ",", "local", "global", "++", "Id", "/", "*", "--")));
		this.follow.put("Const", new HashSet<>(Arrays.asList("typedef")));
		this.follow.put("ExpressaoLR3", new HashSet<>(Arrays.asList("Numero", "while", "(", "if", "local", "--", "true", "++", "!", "Id", "global", "String", "false")));
		this.follow.put("IdentificadorAritmetico3", new HashSet<>(Arrays.asList("(", "Numero", ";")));
		this.follow.put("CodigosRetornos", new HashSet<>(Arrays.asList("global", "if", "read", "while", "Id", "print", "return", "local")));
		this.follow.put("IdStruct", new HashSet<>(Arrays.asList("typedef", "procedure", "var", "const", "function")));
		this.follow.put("Vetor", new HashSet<>(Arrays.asList("=", "Numero", ";", "(", ",", "local", ")", "--", "*", "Id", "/", "++", "global")));
		this.follow.put("Vetor2", new HashSet<>(Arrays.asList("[", ".")));
		this.follow.put("IdentificadorComandos2_1", new HashSet<>(Arrays.asList("Id", "global", "local")));
		this.follow.put("ListaParametros", new HashSet<>(Arrays.asList(".", "=", "[", "(")));
		this.follow.put("Para2", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.follow.put("Print1", new HashSet<>(Arrays.asList("global", "if", "read", "while", "Id", "print", "return", "local")));
		this.follow.put("IdentificadorSemFuncao", new HashSet<>(Arrays.asList("=", "Numero", "(", ")", "++", ",", "Id", "local", "global", "--")));
		this.follow.put("PrintFim", new HashSet<>(Arrays.asList()));
		this.follow.put("Identificador2", new HashSet<>(Arrays.asList("=", "Numero", "(", ",", "*", ")", "global", "local", "Id", "/", "++", "--")));
		this.follow.put("TipoStruct", new HashSet<>(Arrays.asList("typedef", "procedure", "var", "function", "const")));
		this.follow.put("T", new HashSet<>(Arrays.asList("-", "+")));
		this.follow.put("ExpressaoLR", new HashSet<>(Arrays.asList("Numero", "while", "(", "if", "local", "--", "true", "++", "!", "Id", "global", "String", "false")));
		this.follow.put("ArgumentoLR3", new HashSet<>(Arrays.asList(">", "<", "||", "++", "==", "<=", "!", "Id", "String", "Numero", "!=", "(", "--", ">=", "local", "false", "true", "&&", "global")));
		this.follow.put("Identificador", new HashSet<>(Arrays.asList(".", ")", "[", ",")));
		this.follow.put("E2", new HashSet<>(Arrays.asList("(", "Numero", ";")));
		this.follow.put("Procedimento", new HashSet<>(Arrays.asList("procedure", "function")));
		this.follow.put("IdVar", new HashSet<>(Arrays.asList("const", "function", "while", "return", "local", "read", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("Struct", new HashSet<>(Arrays.asList("const", "procedure", "var", "typedef", "function")));
		this.follow.put("Valor", new HashSet<>(Arrays.asList("=", "[", "Id", ",", ";", ".")));
		this.follow.put("ContListaParametros", new HashSet<>(Arrays.asList("=", "(", "[", ".")));
		this.follow.put("Start", new HashSet<>(Arrays.asList("$")));
		this.follow.put("Var3", new HashSet<>(Arrays.asList("const", "function", "while", "return", "local", "read", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("IdConst", new HashSet<>(Arrays.asList("typedef")));
		this.follow.put("Const3", new HashSet<>(Arrays.asList()));
		this.follow.put("Funcao", new HashSet<>(Arrays.asList("procedure", "function")));
		this.follow.put("Condicional", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("TipoConst", new HashSet<>(Arrays.asList("typedef")));
		this.follow.put("Struct3", new HashSet<>(Arrays.asList("typedef", "procedure", "var", "const", "function")));
		this.follow.put("Parametro", new HashSet<>(Arrays.asList("procedure", "function")));
		this.follow.put("Comandos", new HashSet<>(Arrays.asList("global", "if", "read", "while", "Id", "print", "return", "local")));
		this.follow.put("ExpressaoLR2", new HashSet<>(Arrays.asList("Numero", "while", "(", "if", "local", "false", "true", "global", "!", "Id", "++", "String", "--")));
		this.follow.put("F2", new HashSet<>(Arrays.asList("procedure", "function")));
		this.follow.put("Var4", new HashSet<>(Arrays.asList("const", "function", "while", "return", "local", "read", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("Corpo", new HashSet<>(Arrays.asList("procedure", "while", "function", "start", "if", "else")));
		this.follow.put("Var2", new HashSet<>(Arrays.asList("const", "read", "while", "return", "local", "function", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("IdentificadorComandos", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("IndiceVetor", new HashSet<>(Arrays.asList("[", ".")));
		this.follow.put("TipoVar", new HashSet<>(Arrays.asList("const", "read", "while", "return", "local", "function", "typedef", "procedure", "var", "Id", "print", "if", "global")));
		this.follow.put("Read1", new HashSet<>(Arrays.asList()));
		this.follow.put("Para1", new HashSet<>(Arrays.asList("procedure", "function")));
		this.follow.put("AuxRead", new HashSet<>(Arrays.asList()));
		this.follow.put("ReadFim", new HashSet<>(Arrays.asList()));
		this.follow.put("F", new HashSet<>(Arrays.asList("*", "/")));
		this.follow.put("Extends", new HashSet<>(Arrays.asList("typedef", "procedure", "var", "function", "const")));
		this.follow.put("Const2", new HashSet<>(Arrays.asList()));
		this.follow.put("AuxPrint", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("Para3", new HashSet<>(Arrays.asList("int", "boolean", "Id", "string", "real")));
		this.follow.put("ArgumentoLR", new HashSet<>(Arrays.asList(">", "<", "||", "++", ">=", "<=", "!", "Id", "String", "Numero", "!=", "(", "global", "==", "true", "false", "local", "&&", "--")));
		this.follow.put("Identificador3", new HashSet<>(Arrays.asList(".", ",", "[", ")")));
		this.follow.put("ListaParametros2", new HashSet<>(Arrays.asList(",")));
		this.follow.put("Inicio", new HashSet<>(Arrays.asList("$")));
		this.follow.put("Laco", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("CondEnd", new HashSet<>(Arrays.asList("global", "if", "read", "while", "Id", "print", "return", "local")));
		this.follow.put("GeraFuncaoeProcedure", new HashSet<>(Arrays.asList("const", "procedure", "var", "typedef", "function")));
		this.follow.put("ComandosReturn", new HashSet<>(Arrays.asList("local", "return", "read", "while", "Id", "print", "if", "global")));
		this.follow.put("Escopo", new HashSet<>(Arrays.asList("Id")));
		this.follow.put("IdentificadorAritmetico", new HashSet<>(Arrays.asList(">", "<", ";", "local", "==", "<=", "Id", "Numero", "!=", "-", "+", "*", "global", ">=", "[", "(", ".", "/", "++", "--")));
		this.follow.put("T2", new HashSet<>(Arrays.asList("Numero", "-", "local", "+", "*", "global", "Id", "[", "++", ".", "/", "(", "--")));
		this.follow.put("Corpo2", new HashSet<>(Arrays.asList("}", "read", "while", "return", "local", "print", "var", "Id", "if", "global")));
		this.follow.put("ExpressaoAritmetica2", new HashSet<>(Arrays.asList("(", "Numero", ";")));
		this.follow.put("ExpressaoAritmetica", new HashSet<>(Arrays.asList(">", "<", ";", "local", "==", "<=", "Id", "Numero", "!=", "-", "+", "*", "--", "(", "[", "++", ".", "/", ">=", "global")));
	}

    public HashMap<String, List<List<String>>> getProductions(){
        HashMap<String, List<List<String>>> productions = new HashMap<>();
		productions.put("<ArgumentoLR2_1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Id")), new ArrayList<>(Arrays.asList("true")), new ArrayList<>(Arrays.asList("false")))));
		productions.put("<Read>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'read'", "'('", "<Read1>")))));
		productions.put("<OperadorLogico>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'&&'")), new ArrayList<>(Arrays.asList("'||'")))));
		productions.put("<ArgumentoLR2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'!'", "<ArgumentoLR2_1>")), new ArrayList<>(Arrays.asList("true")), new ArrayList<>(Arrays.asList("false")))));
		productions.put("<Corpo>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Var>", "<Corpo2>", "'}'")), new ArrayList<>(Arrays.asList("'}'")))));
		productions.put("<Var>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'var'", "'{'", "<TipoVar>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Tipo>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'int'")), new ArrayList<>(Arrays.asList("'boolean'")), new ArrayList<>(Arrays.asList("'string'")), new ArrayList<>(Arrays.asList("'real'")), new ArrayList<>(Arrays.asList("Id")))));
		productions.put("<Print>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'print'", "'('", "<Print1>")))));
		productions.put("<ExpressaoLogicaRelacional>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<ExpressaoLR>")), new ArrayList<>(Arrays.asList("'('", "<ExpressaoLR>", "')'", "<ExpressaoLR3>")))));
		productions.put("<Struct2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<IdStruct>")), new ArrayList<>(Arrays.asList("';'", "<Struct3>")))));
		productions.put("<OperadorRelacional>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'!='")), new ArrayList<>(Arrays.asList("'=='")), new ArrayList<>(Arrays.asList("'<'")), new ArrayList<>(Arrays.asList("'>'")), new ArrayList<>(Arrays.asList("'<='")), new ArrayList<>(Arrays.asList("'>='")))));
		productions.put("<Identificador4>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'.'", "Id", "<Vetor>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Const>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'const'", "' { '", "<TipoConst>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<ExpressaoLR3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<OperadorLogico>", "<ExpressaoLogicaRelacional>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<IdentificadorAritmetico3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Identificador2>", "<ExpressaoAritmetica2>")), new ArrayList<>(Arrays.asList("'('", "<ListaParametros>", "')'", "<T2>", "<E2>")))));
		productions.put("<CodigosRetornos>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("';'")), new ArrayList<>(Arrays.asList("<ExpressaoAritmetica>", "';'")))));
		productions.put("<Escopo>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'local'", "'.'")), new ArrayList<>(Arrays.asList("'global'", "'.'")))));
		productions.put("<Vetor>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'['", "<IndiceVetor>", "']'", "<Vetor2>", "<Identificador4>")), new ArrayList<>(Arrays.asList("<Identificador4>")))));
		productions.put("<Vetor2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'['", "<IndiceVetor>", "']'")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<T2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'*'", "<ExpressaoAritmetica>")), new ArrayList<>(Arrays.asList("'/'", "<ExpressaoAritmetica>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<ListaParametros>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<ListaParametros2>", "<ContListaParametros>")))));
		productions.put("<Para2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'['", "']'", "<Para3>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Print1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("String", "<AuxPrint>")), new ArrayList<>(Arrays.asList("<Identificador>", "<AuxPrint>")), new ArrayList<>(Arrays.asList("Numero", "<AuxPrint>")))));
		productions.put("<IdentificadorSemFuncao>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Escopo>", "Id", "<Identificador2>")), new ArrayList<>(Arrays.asList("Id", "<Identificador2>")))));
		productions.put("<PrintFim>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("')'", "';'")))));
		productions.put("<Identificador2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'.'", "Id", "<Vetor>")), new ArrayList<>(Arrays.asList("<Vetor>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<TipoStruct>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Tipo>", "<IdStruct>")))));
		productions.put("<T>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<F>", "<T2>")))));
		productions.put("<ExpressaoLR>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<ArgumentoLR2>", "<ExpressaoLR2>")), new ArrayList<>(Arrays.asList("<ArgumentoLR3>", "<OperadorRelacional>", "<ArgumentoLR>", "<ExpressaoLR3>")))));
		productions.put("<ArgumentoLR3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("String")), new ArrayList<>(Arrays.asList("<ExpressaoAritmetica>")))));
		productions.put("<Identificador>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Escopo>", "Id", "<Identificador2>")), new ArrayList<>(Arrays.asList("Id", "<Identificador3>")))));
		productions.put("<E2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'+'", "<ExpressaoAritmetica>")), new ArrayList<>(Arrays.asList("'-'", "<ExpressaoAritmetica>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Procedimento>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'procedure'", "Id", "'('", "<Parametro>")))));
		productions.put("<IdVar>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Id", "<Var2>")))));
		productions.put("<Struct>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'typedef'", "'struct'", "Id", "<Extends>", "<TipoStruct>", "<Struct>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Valor>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Numero")), new ArrayList<>(Arrays.asList("String")), new ArrayList<>(Arrays.asList("Boolean")), new ArrayList<>(Arrays.asList("Id")))));
		productions.put("<ContListaParametros>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<ListaParametros>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<Start>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'start'", "'('", "')'", "'{'", "<Corpo>", "'}'")))));
		productions.put("<Var3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'}'")), new ArrayList<>(Arrays.asList("<TipoVar>")))));
		productions.put("<IdConst>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Id", "<Valor>", "<Const2>")))));
		productions.put("<Const3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("' } '")), new ArrayList<>(Arrays.asList("<TipoConst>")))));
		productions.put("<Funcao>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'function'", "<Tipo>", "Id", "'('", "<Parametro>")))));
		productions.put("<Const2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("' , '", "<IdConst>")), new ArrayList<>(Arrays.asList("' ; '", "<Const3>")))));
		productions.put("<TipoConst>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Tipo>", "<IdConst>")))));
		productions.put("<Struct3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'}'")), new ArrayList<>(Arrays.asList("<TipoStruct>")))));
		productions.put("<Parametro>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Tipo>", "Id", "<Para2>", "<Para1>")))));
		productions.put("<ComandosReturn>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'return'", "<CodigosRetornos>")))));
		productions.put("<IdentificadorComandos2_1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<ExpressaoAritmetica>")), new ArrayList<>(Arrays.asList("String")), new ArrayList<>(Arrays.asList("Boolean")))));
		productions.put("<F2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'{'", "<Corpo>")))));
		productions.put("<Var4>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<IdVar>")), new ArrayList<>(Arrays.asList("';'", "<Var3>")))));
		productions.put("<IdentificadorComandos2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'='", "<IdentificadorComandos2_1>")), new ArrayList<>(Arrays.asList("'('", "<ListaParametros>", "')'")))));
		productions.put("<IdentificadorComandos>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<IdentificadorSemFuncao>", "<IdentificadorComandos2>", "';'")))));
		productions.put("<Comandos>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Condicional>")), new ArrayList<>(Arrays.asList("<Laco>")), new ArrayList<>(Arrays.asList("<Read>")), new ArrayList<>(Arrays.asList("<Print>")), new ArrayList<>(Arrays.asList("<ComandosReturn>")), new ArrayList<>(Arrays.asList("<IdentificadorComandos>")))));
		productions.put("<IndiceVetor>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("IntPos")), new ArrayList<>(Arrays.asList("<Identificador>")))));
		productions.put("<TipoVar>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Tipo>", "<IdVar>")))));
		productions.put("<F>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'('", "<ExpressaoAritmetica>", "')'")), new ArrayList<>(Arrays.asList("Numero")))));
		productions.put("<Para1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Parametro>")), new ArrayList<>(Arrays.asList("')'", "<F2>")))));
		productions.put("<ReadFim>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("')'", "';'")))));
		productions.put("<AuxRead>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Read1>")), new ArrayList<>(Arrays.asList("<ReadFim>")))));
		productions.put("<Read1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<IdentificadorSemFuncao>", "<AuxRead>")))));
		productions.put("<Extends>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'extends'", "Id", "'{'")), new ArrayList<>(Arrays.asList("'{'")))));
		productions.put("<AuxPrint>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Print1>")), new ArrayList<>(Arrays.asList("<PrintFim>")))));
		productions.put("<Identificador3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Identificador2>")), new ArrayList<>(Arrays.asList("'('", "<ListaParametros>", "')'")))));
		productions.put("<Para3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'['", "']'")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<ArgumentoLR>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<ArgumentoLR2>")), new ArrayList<>(Arrays.asList("<ArgumentoLR3>")))));
		productions.put("<ExpressaoAritmetica2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'++'", "<T2>", "<E2>")), new ArrayList<>(Arrays.asList("'--'", "<T2>", "<E2>")), new ArrayList<>(Arrays.asList("<T2>", "<E2>")))));
		productions.put("<ListaParametros2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Identificador>")), new ArrayList<>(Arrays.asList("Numero")), new ArrayList<>(Arrays.asList("String")))));
		productions.put("<Inicio>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Const>", "<Struct>", "<Var>", "<GeraFuncaoeProcedure>", "<Start>")))));
		productions.put("<Laco>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'while'", "'('", "<ExpressaoLogicaRelacional>", "')'", "'{'", "<Corpo>", "'}'")))));
		productions.put("<CondEnd>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'else'", "'{'", "<Corpo>", "'}'")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<GeraFuncaoeProcedure>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Funcao>", "<GeraFuncaoeProcedure>")), new ArrayList<>(Arrays.asList("<Procedimento>", "<GeraFuncaoeProcedure>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<ExpressaoLR2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<OperadorRelacional>", "<ArgumentoLR>", "<ExpressaoLR3>")), new ArrayList<>(Arrays.asList("<ExpressaoLR3>")))));
		productions.put("<Var2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<IdVar>")), new ArrayList<>(Arrays.asList("';'", "<Var3>")), new ArrayList<>(Arrays.asList("'='", "<Valor>", "<Var4>")), new ArrayList<>(Arrays.asList("<Vetor>", "<Var4>")))));
		productions.put("<IdentificadorAritmetico>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Escopo>", "Id", "<Identificador2>", "<ExpressaoAritmetica2>")), new ArrayList<>(Arrays.asList("Id", "<IdentificadorAritmetico3>")))));
		productions.put("<Condicional>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'if'", "'('", "<ExpressaoLogicaRelacional>", "')'", "'then'", "'{'", "<Corpo>", "'}'", "<CondEnd>")))));
		productions.put("<Corpo2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Comandos>", "<Corpo2>")), new ArrayList<>(Arrays.asList("")))));
		productions.put("<IdStruct>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Id", "<Struct2>")))));
		productions.put("<ExpressaoAritmetica>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<T>", "<E2>")), new ArrayList<>(Arrays.asList("<IdentificadorAritmetico>")), new ArrayList<>(Arrays.asList("'++'", "<IdentificadorSemFuncao>", "<T2>", "<E2>")), new ArrayList<>(Arrays.asList("'--'", "<IdentificadorSemFuncao>", "<T2>", "<E2>")))));
		return productions;
	}

    public HashMap<String, HashSet<String>> getFirst(){
        return this.first;
    }

    public HashMap<String, HashSet<String>> getFollow(){
        return this.follow;
    }

    public static FirstFollow getInstance(){
        if(instance == null){
            instance = new FirstFollow();
        }
        return instance;
    }
}

